tsubuyaki_22_nov-master/config/routes.rb
Rails.application.routes.draw do

  resource :registrations, only: [:new, :create]
  resource :sessions, only: [:new, :create, :destroy]
  resource :settings, only: [:edit, :update]

  resources :users, only: [:index, :show] do
    resource :follows, only: [:create, :destroy]
    get :favorites, on: :member
    get :follows, on: :member
    get :followers, on: :member
  end

  resources :tweets do
    resource :favorites, only: [:create, :destroy]
    get :timeline, on: :collection
  end

  root to: 'registrations#new'

end

tsubuyaki_22_nov-master/app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password

  has_many :microposts
  has_many :relationships
  has_many :followings, through: :relationships, source: :follow
  has_many :reverses_of_relationship, class_name: 'Relationship', foreign_key: 'follow_id'
  has_many :followers, through: :reverses_of_relationship, source: :user
  
  has_many :favorites
  has_many :favoritings, through: :favorites, source: :favorite
  has_many :reverses_of_favorite, class_name: 'Favorite', foreign_key: 'favorite_id'
  has_many :favoriters, through: :reverses_of_favorite, source: :user

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  def following?(other_user)
    self.followings.include?(other_user)
  end
end

tsubuyaki_22_nov-master/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_login

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])
  end

  def favorites
    @user = User.find(params[:id])
  end

  def follows
    @user = User.find(params[:id])
  end

  def followers
    @user = User.find(params[:id])
  end
end

tsubuyaki_22_nov-master/app/helpers/users_helper.rb
module UsersHelper
  def render_user_screen_name user
    if user.screen_name.blank?
      user.name
    else
      user.screen_name
    end
  end
end

tsubuyaki_22_nov-master/app/views/users/_header.html.haml
.user-info
  - if notice
    .alert.alert-info= notice
  %span.user-name
    = render_user_screen_name(@user)
  %span.user-id
    @#{@user.name}
  .bio
    = @user.bio

%ul.nav.nav-tabs.nav-justified
  %li{ class: action_name == "show" ? "active" : nil }
    = link_to user_path(@user) do
      .text
        つぶやき
      .num
        #{@user.tweets.count}
  %li{ class: action_name == "follows" ? "active" : nil }
    = link_to follows_user_path(@user) do
      .text
        フォロー
      .num
        #{@user.inverse_followers.count}
  %li{ class: action_name == "followers" ? "active" : nil }
    = link_to followers_user_path(@user) do
      .text
        フォロワー
      .num
        #{@user.followers.count}
  %li{ class: action_name == "favorites" ? "active" : nil }
    = link_to favorites_user_path(@user) do
      .text
        お気に入り
      .num
        #{@user.favorites.count}

tsubuyaki_22_nov-master/app/views/users/_tweet.html.haml
= div_for tweet, class: "list-group-item" do |t|
  %h4.user
    %span.user-name
      = link_to t.user.name, user_path(t.user)
    %span.user-id
      @#{t.user.name}
    %span.time.pull-right
      = distance_of_time_in_words_to_now(t.created_at)
    .clear
  .tweet-content
    %p
      = t.content
    .content-footer
      - if t.favorited_by? current_user
        = link_to "お気に入りの解除", tweet_favorites_path(t), method: :delete
      - else
        = link_to "お気に入りに登録", tweet_favorites_path(t), method: :post
      - if t.user.followed_by? current_user
        = link_to "フォロー解除", user_follows_path(t.user), method: :delete
      - else
        = link_to "フォロー", user_follows_path(t.user), method: :post

tsubuyaki_22_nov-master/app/views/users/_user.html.haml
= div_for user, class: "list-group-item" do |u|
  %h4.user
    %span.user-name
      = link_to u.name, user_path(u)
    %span.user-id
      @#{u.name}
  .bio
    = u.bio
  .follow-unfollow
    - if u.followed_by? current_user
      = link_to "フォロー解除", user_follows_path(u), method: :delete
    - else
      = link_to "フォロー", user_follows_path(u), method: :post

tsubuyaki_22_nov-master/app/views/users/favorites.html.haml
.col-xs-8#users-content
  = render partial: "users/header"
  .list-group
    - if @user.favorites.empty?
      .list-group-item
        まだお気に入りに登録されたツイートはありません
    = render partial: "users/tweet", collection: @user.favorites.map{|f| f.tweet }

tsubuyaki_22_nov-master/app/views/users/followers.html.haml
.col-xs-8#users-content
  = render partial: "users/header"
  .list-group
    = render @user.followers

tsubuyaki_22_nov-master/app/views/users/follows.html.haml
.col-xs-8#users-content
  = render partial: "users/header"
  .list-group
    = render @user.inverse_followers

tsubuyaki_22_nov-master/app/views/users/index.html.haml
.col-xs-8#users-content
  .list-group
    .list-group-item.user-list
      %h2 ユーザー一覧
    = render partial: "users/user", collection: @users

tsubuyaki_22_nov-master/app/views/users/show.html.haml
.col-xs-8#users-content
  = render partial: "users/header"
  .list-group
    - if @user.tweets.empty?
      .list-group-item
        まだツイートはありません
    = render partial: "users/tweet", collection: @user.tweets